#      params:
#        wht_account: "Expenses:Shopping:Amazon"
#        ignore_bank_categories: True

importers:
  # Importer key also corresponds to the subdirectory in the beancount_import_data
  # directory where the csv files will be looked up
  # Possible "importer" values are "monzo", "revolut" and "wise"
  # You can use different accounts for different directories
  # amazon:
  #   importer: amazon
  #   account: Assets:DE:Comdirect:Checking
  #   currency: EUR
  
  comdirect:
    importer: comdirect
    account: Assets:DE:Comdirect:Checking
    currency: EUR
  
  # sparda:
  #   importer: sparda
  #   account: Assets:DE:Sparda:Checking
  #   currency: EUR
  
  # google:
  #   importer: google
  #   account: Assets:DE:Comdirect:Checking
  #   currency: EUR
  
  paypal:
   importer: paypal
   email_address: georg.hametner@googlemail.com
   account: Assets:EU:PayPal
   checking_account: Assets:DE:Comdirect:Checking
   commission_account: Expenses:Financial:Commission
   currency: EUR